sp:
  user-service:
    users: "[{\":7,\"username\":\"abc\",\"password\":\"123\"},
             {\":8,\"username\":\"def\",\"password\":\"456\"},
             {\":9,\"username\":\"ghi\",\"password\":\"789\"}]"

            
spring:
  application:
    name: user-service
  rabbitmq:
    host: 192.168.174.128
    port: 5672
    username: admin
    username: admin
    
server:
  port: 8101
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka,http://eureka2:2002/eureka
      
      
managment:
  endpoints:
    web:
      exposure:
        include: refresh
        
